dataset:
  build_problem: dolfin_problems.BuildPoissonProblem
  mesh: ../data/square_mesh.xml
  path: ../data/poisson_dataset.hdf5
  reduced_functional: true
model:
  args:
    model_kwargs:
      blocks_per_stage: 2
      conv_stride: 2
      input_dims: 3
      num_stages: 3
      output_dims: 1
      stage_dims: 16
    model_type: models.UNet
    positive_definite: true
  class_path: dolfin_pbnn.DolfinPBNN
  weights: ../models/Poisson/DolfinUNet/model_weight.ckpt
optimizer:
  args:
    lr: 0.001
  class_path: torch.optim.Adam
save_path: ../models/Poisson/DolfinUNet
scheduler:
  args:
    gamma: 0.99
  class_path: torch.optim.lr_scheduler.ExponentialLR
training:
  batch_size: 16
  epochs: 200
