dataset:
    path: ../data/elasticity_adhesion_dataset.hdf5
    mesh: ../data/circle_mesh.xml
    build_problem: dolfin_problems.BuildElasticityAdhesionProblem

model:
    class_path: dolfin_pbnn.DolfinPBNN
    args:
        input_dim: 3
        output_dim: 1
        num_hidden: 8
        hidden_dim: 64
        dropout_rate: 0.1

optimizer:
    class_path: torch.optim.Adam
    args:
        lr: 0.001

scheduler:
    class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
    args:
        patience: 10
        factor: 0.5
        min_lr: 0.0000001

training:
    epochs: 100
    batch_size: 16

save_path: ../models/ElasticityAdhesion