dataset:
    method_path: data_processing.load_burgers_1d_data
    args:
        path: ../data/Burgers/burgers_data_R10.mat
        space_resolution: 1
        positional_encoding: True
        validation_split: 0.2
        random_seed: 42

loader:
    batch_size: 32
    shuffle: True
    num_workers: 4
    pin_memory: True

model:
    class_path: fno_1d.FNO1d
    args:
        in_channels: 2
        out_channels: 1
        fno_channels: 32
        modes: 16
        fno_pad: 0

optimizer:
    class_path: torch.optim.Adam
    args:
        lr: 0.003

scheduler:
    class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
    args:
        patience: 10

training:
    num_epochs: 10

save_path: ../models/Burgers_1d/