dataset:
  build_problem: dolfin_problems.BuildStokesProblem
  mesh: ../data/square_mesh.xml
  path: ../data/stokes_dataset.hdf5
  reduced_functional: false
model:
  args:
    model_kwargs:
      hidden_dims: 64
      input_dims: 3
      num_hidden: 8
      output_dims: 2
    model_type: models.LatentNet
    positive_definite: false
  class_path: torch_pbnn.TorchPBNN
  weights: ../models/Stokes/TorchLatentNet/model_weight.ckpt
optimizer:
  args:
    lr: 0.001
  class_path: torch.optim.Adam
save_path: ../models/Stokes/TorchLatentNet
scheduler:
  args:
    gamma: 0.99
  class_path: torch.optim.lr_scheduler.ExponentialLR
training:
  batch_size: 16
  epochs: 200
