dataset:
  args:
    positional_encoding: true
    space_resolution: 2
    train_path: ../data/Darcy/piececonst_r421_N1024_smooth1.mat
    val_path: ../data/Darcy/piececonst_r421_N1024_smooth1.mat
  method_path: data_processing.load_darcy_2d_data
loader:
  batch_size: 32
  num_workers: 4
  pin_memory: true
  shuffle: true
model:
  args:
    fno_channels: 32
    fno_pad: 0
    in_channels: 3
    modes:
    - 16
    - 16
    out_channels: 1
  class_path: fno_2d.FNO2d
  weights: ../models/Darcy_2d//model_weight.ckpt
optimizer:
  args:
    lr: 0.003
  class_path: torch.optim.Adam
save_path: ../models/Darcy_2d/
scheduler:
  args:
    patience: 10
  class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
training:
  num_epochs: 50
